Fix 'HasKey' scope lookup by changing ordering
With gcc 4.8.5 the below error occurs when building and this commit
fixes this issue.

In file included from
./include/wila/core.hpp:10:0,
                 from tests/common.h:5,
                 from tests/main.cpp:19:
./include/wila/utils.hpp: In instantiation of ‘std::map<K, V> mhcpp::utils::
Subset(const std::vector<_RealType>&, const std::map<K, V>&, bool) [with K = std::basic_string<char>; V = std::basic_string<char>]’:
tests/main.cpp:834:43:   required from here
./include/wila/utils.hpp:181:24: error: ‘HasKey’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
     if (!HasKey(dict, k) && !allowMissing)
                        ^
./include/wila/utils.hpp:190:8: note: ‘template<class K, class V> bool mhcpp::utils::HasKey(const std::map<K, V>&, const string&)’ declared here, later in the translation unit
   bool HasKey(const std::map<K, V>& dict, const string& key)
        ^